# BANNERSTART
# - Copyright 2009, Galois, Inc.
# - This software is distributed under a standard, three-clause BSD license.
# - Please see the file LICENSE, distributed with this software, for specific
# - terms and conditions.
# Author: Adam Wick <awick@galois.com>
# BANNEREND
#
BINARIES=Time
include ../../standard.mk

run: Time
	sudo xl create Time.config -c 'extra="count=10"'

