module Config where
cProjectName          :: String
cProjectName          = "The Glorious Glasgow Haskell Compilation System (HaLVM version)"
cProjectVersion       :: String
cProjectVersion       = "6.12.3"
cProjectVersionInt    :: String
cProjectVersionInt    = "612"
cProjectPatchLevel    :: String
cProjectPatchLevel    = "3"
cBooterVersion        :: String
cBooterVersion        = "6.12.3"
cStage                :: String
cStage                = show (2 :: Int)
cIntegerLibrary       :: String
cIntegerLibrary       = "@INTEGER_LIBRARY@"
cSplitObjs            :: String
cSplitObjs            = "YES"
cGhcWithInterpreter   :: String
cGhcWithInterpreter   = "YES"
cGhcWithNativeCodeGen :: String
cGhcWithNativeCodeGen = "YES"
cGhcWithSMP           :: String
cGhcWithSMP           = "YES"
cGhcRTSWays           :: String
cGhcRTSWays           = "l thr "
cGhcUnregisterised    :: String
cGhcUnregisterised    = "NO"
cGhcEnableTablesNextToCode :: String
cGhcEnableTablesNextToCode = "YES"
cLeadingUnderscore    :: String
cLeadingUnderscore    = "NO"
cRAWCPP_FLAGS         :: String
cRAWCPP_FLAGS         = "-undef -traditional"
cGCC                  :: String
cGCC                  = "/usr/bin/gcc"
cMKDLL                :: String
cMKDLL                = "dllwrap"
cLdIsGNULd            :: String
cLdIsGNULd            = "YES"
cLD_X                 :: String
cLD_X                 = "-x"
cGHC_DRIVER_DIR       :: String
cGHC_DRIVER_DIR       = "driver"
cGHC_TOUCHY_PGM       :: String
cGHC_TOUCHY_PGM       = "touchy"
cGHC_TOUCHY_DIR       :: String
cGHC_TOUCHY_DIR       = "utils/touchy"
cGHC_UNLIT_PGM        :: String
cGHC_UNLIT_PGM        = "unlit"
cGHC_UNLIT_DIR        :: String
cGHC_UNLIT_DIR        = "utils/unlit"
cGHC_MANGLER_PGM      :: String
cGHC_MANGLER_PGM      = "ghc-asm"
cGHC_MANGLER_DIR      :: String
cGHC_MANGLER_DIR      = "driver/mangler"
cGHC_SPLIT_PGM        :: String
cGHC_SPLIT_PGM        = "ghc-split"
cGHC_SPLIT_DIR        :: String
cGHC_SPLIT_DIR        = "driver/split"
cGHC_SYSMAN_PGM       :: String
cGHC_SYSMAN_PGM       = ""
cGHC_SYSMAN_DIR       :: String
cGHC_SYSMAN_DIR       = "rts/parallel"
cGHC_CP               :: String
cGHC_CP               = "cp"
cGHC_PERL             :: String
cGHC_PERL             = "/usr/bin/perl"
cEnableWin32DLLs      :: String
cEnableWin32DLLs      = ""
cCONTEXT_DIFF         :: String
cCONTEXT_DIFF         = "diff -U 1"
cUSER_WAY_NAMES       :: String
cUSER_WAY_NAMES       = ""
cUSER_WAY_OPTS        :: String
cUSER_WAY_OPTS        = ""
cDEFAULT_TMPDIR       :: String
cDEFAULT_TMPDIR       = "/tmp"
cRelocatableBuild     :: Bool
cRelocatableBuild     = False
cLibFFI               :: Bool
cLibFFI               = False
