#!/bin/sh
# BANNERSTART
# - Copyright 2006-2008, Galois, Inc.
# - This software is distributed under a standard, three-clause BSD license.
# - Please see the file LICENSE, distributed with this software, for specific
# - terms and conditions.
# Author: Adam Wick <awick@galois.com>
# BANNEREND
LIBDIR_REL=`echo $0 | sed 's!/[^/]*$!!g'`
CURDIR=`pwd`
cd ${LIBDIR_REL}
LIBDIR=`pwd`
cd ${CURDIR}
tflag="--template=${LIBDIR}/template-hsc.h"

ARGS=""
while [ $# != 0 ] ; do
  case "$1" in
    --ld*) IGNORE="Foo!"; shift;;
    --cc*) CC=`which gcc`; ARGS="${ARGS} --cc=${CC}"; shift;;
    --cflag=-package*) IGNORE="Foo!"; shift; shift;;
    --lflag=-optl*) sub=`echo $1 | sed 's/-optl//g'`;
                    ARGS="$ARGS ${sub}";
                    shift;;
    *) ARGS="$ARGS $1"; shift;;
  esac
done

CMD="${LIBDIR}/hsc2hs-bin $ARGS $tflag --cflag=-I${LIBDIR}/include --lflag=-lc --cflag=-D__GLASGOW_HASKELL__=608"
#echo ${CMD}
$CMD
