# BANNERSTART
# - Copyright 2006-2008, Galois, Inc.
# - This software is distributed under a standard, three-clause BSD license.
# - Please see the file LICENSE, distributed with this software, for specific
# - terms and conditions.
# Author: Magnus Carlsson <magnus@galois.com>
# BANNEREND

HALVM_SRCS=consoleTest.hs
TEST_SUBJECTS=consoleTest
TEST_VMS=consoleTest
QEMU_TEST=y
DISK_IMG=consoleTest.img
VERBOSE_TEST=--verbose

all: test

include ../../mk/tests.mk

DISK_SIZE=5000000

